version: "3.7"
services:
  api:
    image: node:12
    command: sh -c "npm install && npm run start:api"
    ports:
      - 3333:3333
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - .env
    depends_on:
      - "mysql"
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - chat-mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: chatandcall
volumes:
  chat-mysql-data:
